application: ee445l-fm7869
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$
  
- url: .*
  script: main.application

libraries:
- name: webapp2
  version: "2.5.2"
